version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  teledown:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - ./downloads:/app/downloads
      - ./cache:/app/cache
      - ./session:/app/session
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data: