services:
  teledown:
    build: .
    volumes:
      - .:/app
      - ./downloads:/app/downloads
      - ./session:/app/session
    env_file:
      - .env
    stdin_open: true  # Docker -i
    tty: true        # Docker -t
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"     # Changed from unless-stopped to prevent auto-restart loop
    init: true       # Add proper init process handling

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data: