services:
  teledown:
    build: .
    volumes:
      - .:/app
      - ./downloads:/app/downloads
      - ./session:/app/session
    env_file:
      - .env
    stdin_open: true  # Permite entrada interativa
    tty: true        # Aloca um pseudo-TTY
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: